# File: keycloak-event-gateway/.gitlab-ci.yml

image: registry.gitlab.com/avcompris/kalisio/avc-kalisio-workspace/avcompris/kalisio-workspace
variables:
  # MAVEN_CLI_OPTS: "-s .gitlab-ci/settings.xml --batch-mode --errors --fail-at-end --show-version"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
  MAVEN_OPTS: "-Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/repository -Djava.awt.headless=true"
  MAVEN_PROFILE: gitlab
  DOCKER_HOST: tcp://172.17.0.1:2375
cache:
  key: ALL
  paths:
    - .m2/repository/

stages:
  - build
  - test

maven:
  stage: build
  only:
    refs:
      - master
  script:
    - mvn ${MAVEN_CLI_OPTS} -P${MAVEN_PROFILE} clean install


docker_build:
  stage: build
  only:
    refs:
      - master
  script:
    - ./build.sh

mocha:
  stage: test
  only:
    refs:
      - master
  artifacts:
    when: always
    paths:
      - test/screenshots
  before_script:
    - cd ${CI_PROJECT_DIR}/test
    - docker-compose down
    - docker-compose up -d
    - ../scripts/wait_for_docker_container.sh test_keycloak_1 "Running the server in development mode."
    - ../scripts/wait_for_docker_container.sh test_selenium_1 "Started Selenium Standalone"
  script:
    - cd ${CI_PROJECT_DIR}/test
    - npm install
    - export SELENIUM_REMOTE_URL=http://172.17.0.1:4444/wd/hub
    - npx mocha integration_tests.js
  after_script:
    - cd ${CI_PROJECT_DIR}/test
    - docker-compose down
