# File: keycloak-event-gateway/docker-compose.yml
#

version: '3'

services:

  keycloak:
      image: quay.io/keycloak/keycloak:22.0.5
      command: start-dev
      environment:
        KC_HOSTNAME: localhost
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: Pass;word1
      volumes:
        - ./target/keycloak-event-gateway-0.0.1-SNAPSHOT.jar:/opt/keycloak/providers/keycloak-event-gateway.jar:ro
      ports:
        - 8080:8080
