version: '3'

services:

  postgres:
      image: postgres
      volumes:
        - keycloak-feathers-broker-postgres:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password

  keycloak:
      image: quay.io/keycloak/keycloak:22.0.5
      command: start-dev \
        --spi-events-listener-feathers-emitter-endpoint=http://localhost:8082
      environment:
        KC_DB: postgres
        KC_DB_URL_HOST: postgres
        KC_DB_USERNAME: keycloak
        KC_DB_PASSWORD: password
        KC_HOSTNAME: localhost
        KC_DB_SCHEMA: public
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: Pass;word1
      volumes:
      - ./target/feathers-emitter-24.0.2.jar://opt/keycloak/providers/feathers-emitter.jar
      ports:
        - 8080:8080
      depends_on:
        - postgres

volumes:
  keycloak-feathers-broker-postgres:
